name: Build and Publish Image to GCR

on:
  push:
    branches:
      - cd/deploy-to-vms

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup GCloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Copy files
        run: gcloud compute scp --zone=europe-west3-c ./docker-compose.yml ./application.yml instance-1:~
      - name: SSH
        run: gcloud compute ssh instance-1 --zone=europe-west3-c --comand=="docker-compose up -d"