name: Deploy three validators network

on:
  repository_dispatch:
    types: [TEST-trigger-image-release]

env:
  refresh_containers_command: docker-compose stop && docker-compose rm -f && docker-compose pull && docker-compose up -d

jobs:
  deploy_previewnet_alice:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "🍏 This job's status is ${{ job.status }}."
