name: Testnet Build and Publish Image to GCR #TODO: different name for mainnet

on:
  push:
    branches:
      - test/workflows #TODO: testnet/mainnet branch
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: echo "🍏 This job's status is ${{ job.status }}."
