name: Testnet Build and Publish Image to GCR #TODO: different name for mainnet

on:
  push:
    tags:
      - '*-rc-*' #TODO: mainnet '*-alpha-*' tag name convention
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ endsWith(github.event.base_ref, 'workflows') }} #TODO: mainnet or testnet branch name
    steps:
      - uses: actions/checkout@v2
      
      - run: echo "TAG NAME ${GITHUB_REF/refs\/tags\//}"
      
      - run: echo "github base ref ${{ github.event.base_ref }}"
      - run: echo " if ! ends with workflows ${{ !endsWith(github.event.base_ref, 'workflows') }}"
      - run: echo " if ends with workflows ${{ endsWith(github.event.base_ref, 'workflows') }}"
      
      - name: Exit if not on workflows branch
        if: ${{ !endsWith(github.event.base_ref, 'workflows') }}
        run:  echo "Branch is WRONG-SKIP. IF endsWith workflows FALSE"
        
    
      - name: DO stuff on workflows branch
        if: ${{ endsWith(github.event.base_ref, 'workflows') }}
        run:  echo "Branch is workflows. OK."

      - run: echo "🍏 This job's status is ${{ job.status }}."
   

   
   
#       - name: Setup GCloud SDK
#         uses: google-github-actions/setup-gcloud@v0.2.0
#         with:
#           project_id: ${{ secrets.GCP_PROJECT }}
#           service_account_key: ${{ secrets.GCP_SA_KEY }}

#       - name: Authorize Docker
#         run: gcloud auth configure-docker

# TODO Testnet 

#       - name: Build and Push Container
#         run: |-
#           docker build \
#             -t gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.SERVICE }}:${GITHUB_REF/refs\/tags\//} \
#             -f build/Dockerfile .
#           docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.SERVICE }}:${GITHUB_REF/refs\/tags\//}

# TODO Mainnet

#       - name: Build and Push Container
#         run: |-
#           docker build \
#             -t gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.SERVICE }}:${GITHUB_REF/refs\/tags\//} \
#             -t gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.SERVICE }}:latest \
#             -f build/Dockerfile .
#           docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.SERVICE }}:${GITHUB_REF/refs\/tags\//}
#           docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.SERVICE }}:latest
