name: Testnet Build and Publish Image to GCR #TODO: different name for mainnet

on:
  push:
    tags:
      - '*-rc-*' #TODO: mainnet '*-alpha-*'
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
#       - run: echo " tag_name ${{ github.event.release.tag_name }}."
      
#       - run: echo "Test with if"
      
#       - run: echo "Test 2. Tag is ${GITHUB_REF/refs\/tags\//}"
#       - run: echo "github ref is ${{ github.ref }}"
      
      - run: echo "github base ref ${{ github.event.base_ref }}"
            
#       - run: echo " if not ends with test/workflows ${{ !endsWith(github.head_ref, 'test/workflows') }}"
      - run: echo " if not ends with workflows ${{ !endsWith(github.head_ref, 'workflows') }}"
      
#       - run: echo "github head ref ${{ github.head_ref }}"
      
#       - run: echo "github event name ${{ github.event_name }}"
      
      - name: Exit if not on test/workflows branch
        if: ${{ !endsWith(github.head_ref, 'workflows') }}
        run:  echo "Branch is WRONG-SKIP. IF endsWith workflows FALSE"
#         run: exit -1
      
      - name: Exit if on test/workflows branch
        if: ${{ endsWith(github.head_ref, 'workflows') }}
        run:  echo "Branch is OK-GO. IF endsWith workflows TRUE"
#         run: exit -1

      - run: echo "🍏 This job's status is ${{ job.status }}."
   
   
#       - name: Setup GCloud SDK
#         uses: google-github-actions/setup-gcloud@v0.2.0
#         with:
#           project_id: ${{ secrets.GCP_PROJECT }}
#           service_account_key: ${{ secrets.GCP_SA_KEY }}

#       - name: Authorize Docker
#         run: gcloud auth configure-docker

# TODO Testnet 

#       - name: Build and Push Container
#         run: |-
#           docker build \
#             -t gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.SERVICE }}:${GITHUB_REF/refs\/tags\//} \
#             -f build/Dockerfile .
#           docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.SERVICE }}:${GITHUB_REF/refs\/tags\//}

# TODO Mainnet

#       - name: Build and Push Container
#         run: |-
#           docker build \
#             -t gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.SERVICE }}:${GITHUB_REF/refs\/tags\//} \
#             -t gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.SERVICE }}:latest \
#             -f build/Dockerfile .
#           docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.SERVICE }}:${GITHUB_REF/refs\/tags\//}
#           docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.SERVICE }}:latest
